baseURL = "https://markus.atelierschork.com"
#disqusShortname = "username"
googleAnalytics = ""
languageCode = "en-us"
theme = "markus"
title = "Hello World!"

[params]
author = "Markus Schork"
description = "Personal blog from Markus Schork"
font = "Open+Sans"
githubusername = "mschork"
highlight = true
highlightlanguages = ["go", "haskell", "kotlin", "scala", "swift"]
#highlightstyle = "solarized-dark"
#showborder = true


#[[menu.icon]]
#name = "stack-overflow"
#url = "https://www.stackoverflow.com/username/"
#weight = 5

#[[menu.icon]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/username/"
#weight = 4

[[menu.main]]
name = "Projects"
url = "/project/"
weight = 3
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
